version: 2.1

jobs:
  run_A3_workflow:
    docker:
      - image: circleci/python:3.10  # Use an appropriate Python image
    working_directory: ~/repo

    steps:
      - checkout  # Checks out your code from the repository

      - run:
          name: Set permissions for the binary
          command: chmod +x venompapa

      - run:
          name: Set up Python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install telebot pymongo aiohttp

      - run:
          name: Run Ven.py
          command: |
            . venv/bin/activate
            python Ven.py

workflows:
  version: 2
  run_a3_workflow:
    triggers:
      - schedule:
          cron: "55 * * * *"  # Runs at 55 minutes past every hour
          filters:
            branches:
              only:
                - main
    jobs:
      - run_A3_workflow
